### ISSUE TITLE
job posts/link spam in list

### ISSUE THREAD

**Issue by altineller** [vmayoral/ros-robotics-companies#46]
Hello,

Some people have committed job posting links in the list. Here is an example:

[^242]: https://www.linkedin.com/jobs/view/3264971272
[^243]: https://www.linkedin.com/jobs/view/3248361044
[^244]: https://www.linkedin.com/jobs/view/3291491344

Best Regards,
Can

**Comment by vmayoral** [comment]
@altineller can't see the example.

If you're referring to the jobs within the footnotes, those are used to link companies to the usage of ROS and ROS 2. Many companies don't advertise it openly and publicly but emphasize the relevance of ROS in their organization through job offers. We're using pointers to those to justify adding them *in some cases*.

Let me know if you still see spam with that in mind.

**Comment by altineller** [comment]
How embarrassing, I forgot to paste the examples.
Yes, I was referring to [238-244] which are in the format of linkedin.com/jobs/view/...
I understand it is justifiable in some context.

Best Regards,
Can
