### ISSUE TITLE
Adding a new company 

### ISSUE THREAD

**Issue by siddarth09** [vmayoral/ros-robotics-companies#61]
Hello sir,
I am working as a robotics intern at @flomobility, FloMobility is a robotics company, which specialized in camera-based autonomy platforms which can be integrated with any vehicle. We are currently working on autonomous lawn mowers which use ROS for the majority of its application such as differential_drive, cameras, battery state, PID Controls, pose_base_controller, apriltag detection and much more. I wanted to add our company to this list of companies since they were arranged alphabetically. How do I make a pull request for the same? please help me out. We use ROS noetic and would also use ROS2 foxy in future

**Comment by vmayoral** [comment]
Head to https://github.com/vmayoral/ros-robotics-companies/pulls and make a Pull Request.

**Comment by siddarth09** [comment]
have created the pull request sir
Thank you
