### ISSUE TITLE
Being able to sort by country/region

### ISSUE THREAD

**Issue by sampreets3** [vmayoral/ros-robotics-companies#66]
Hi, 

It would be great to be able to see what country/countries the company is present in, so that we can potentially search for employment based on geographical area of residence. 

A more concise example of such a use case would be  - I am currently in France, so it would be very interesting for me to see companies that based in France/EU rather than sift through a global list of companies, and then finding out if I can apply to them or not.  

I really admire the work that has been done, thanks a lot for this ! 😀

**Comment by vmayoral** [comment]
@sampreets3 feel free to contribute that directly, it'll be well received. 

Open a PR adding a new column an start doing the research for the listed companies.

**Comment by vmayoral** [comment]
Followed at https://github.com/vmayoral/ros-robotics-companies/pull/68
