### ISSUE TITLE
What is FANUC doing on this list?

### ISSUE THREAD

**Issue by gavanderhoorn** [vmayoral/ros-robotics-companies#70]
Just curious. They're listed under *Active Companies*, but the entry then links to `ros-industrial/fanuc` and the ROS Wiki entry for the same repository/package(s).

As [the readme](https://github.com/ros-industrial/fanuc/tree/8fee5e30e535378758ace26dfdffb8ab0403e23c#status) of that repository makes very clear, there is no FANUC involvement at all there. More accurately, FANUC has not provided any support for their customers using ROS. It's all community, and it always has been.

I haven't checked what the requirements/criteria are for a company to be listed here, but AFAICT, FANUC should be removed.

**Comment by gavanderhoorn** [comment]
Same question for KUKA.

There is no public support for ROS from KUKA.

I'm certain it wasn't the intention, but it doesn't seem fair to OSS contributors to list a company as using/supporting/acknowledging ROS only to link to community supported initiatives.

**Comment by vmayoral** [comment]
I agree with the comments above and this is probably the result of bad research from our side.

@pabloaccelerationrobotics, can you take another pass at this and see whether you can find (other than the existence of a ROS package maintained by third parties) evidence that KUKA and FANUC use ROS?

For ABB, we should remove the pointer to the ROS package if maintained by third parties (not ABB) but I can confirm ABB uses ROS in various of their divisions, specially their new perception group located in Barcelona.

**Comment by gavanderhoorn** [comment]
> I agree with the comments above and this is probably the result of bad research from our side.
> 
> @pabloaccelerationrobotics, can you take another pass at this and see whether you can find (other than the existence of a ROS package maintained by third parties) evidence that KUKA and FANUC use ROS?

Perhaps a definition of the word *use* would be needed.

Having a single employee check out a tutorial or two at one time in the past 10 years would not qualify. Neither would a fleeting collaboration with a partner that is using ROS.

In my opinion both KUKA and FANUC should only appear on this list if you can say without a doubt they are using/supporting/acknowledging ROS, ideally backed by links to available software and/or documentation.

Anything else would seem to give the wrong impression. Especially to users looking to use their products *with ROS* -- which at the moment would lead them to nothing else but community developed and supported packages.

> For ABB, we should remove the pointer to the ROS package if maintained by third parties (not ABB) but I can confirm ABB uses ROS in various of their divisions, specially their new perception group located in Barcelona.

I know, and not just there.

But then the link to `ros-industrial/abb` makes little sense.

**Comment by pabloaccelerationrobotics** [comment]
I have already updated the list, removed FANUC from it.
Corrected the description of ABB and KUKA, where I have added a job offer in which they are looking for people with experience in ROS. The fact that they are looking for ROS engineers specifically is to me an indicator that they use and plan on using ROS.

**Comment by gavanderhoorn** [comment]
> [..] KUKA, where I have added a job offer in which they are looking for people with experience in ROS

From the linkedin post:

> We are opening up an intern position [..]

I would still argue this is not 'evidence' of use of ROS, but as I wrote earlier, perhaps this depends on your definition of *use*.

**Comment by gavanderhoorn** [comment]
Closing as at least the FANUC issue was addressed.

Thanks @pabloaccelerationrobotics.
