### ISSUE TITLE
Remove Robotiq

### ISSUE THREAD

**Issue by gavanderhoorn** [vmayoral/ros-robotics-companies#71]
Similar to #70, I'd suggest removing Robotiq.

*Yes*, there are many, many, community supported, ROS drivers, URDFs and other integrations available, but Robotiq as the company does not support any of them (directly).

Even `ros-industrial/robotiq` is 'just' a community project. Robotiq has indicated at a number of instances they have no interest in maintaining nor offering any ROS support for their products. See again [the readme](https://github.com/ros-industrial/robotiq/tree/45196f6558fe8ba9d89bc8a105396c68c3e7e892#status).

If the only evidence of use-of/support-of ROS was the fact `ros-industrial/robotiq` exists, the Robotiq entry on this list should be removed.

**Comment by vmayoral** [comment]
Thanks for looking at this @gavanderhoorn. Reviews are very much appreciated and welcome (we were hoping someone eventually would take a critical view help us shape it up). Lots to improve in the list.

> If the only evidence of use-of/support-of ROS was the fact ros-industrial/robotiq exists, the Robotiq entry on this list should be removed.

Agreed. We should adopt this.

I'd argue however that Robotiq should be in the list. A few arguments in favour:
- Various conversations with their engineers, including with Samuel (CEO/Founder) confirming their interest in ROS, which is what their clients are asking for
- Though I agree with the above, and the drivers (to my understanding) are a community project, Robotiq's engineering seems to feel slightly different. See https://dof.robotiq.com/discussion/2634/how-to-communicate-to-the-robotiq-2f-85-gripper-via-ros-melodic-and-ur10e:

>  To control the gripper via ros using our ROS package, you need to have it connected directly on your PC.
http://wiki.ros.org/robotiq

Found a few other examples. I believe this can be understood as Robotiq offering ROS support so I'd propose we keep it. dd84dc15efe4b8dbb12ea726b33a15365a465720 attempts to improve this.

**Comment by gavanderhoorn** [comment]
> * Robotiq's engineering seems to feel slightly different. See https://dof.robotiq.com/discussion/2634/how-to-communicate-to-the-robotiq-2f-85-gripper-via-ros-melodic-and-ur10e:

while you are correct they still refer to the packages, this is definitely not evidence of 'support for ROS'. This is just a company referring one of their customers to some external, third-party piece of software.

I guess again this comes down to the definition of *use* here.

Do you believe a reference by an OEM to something which received no support, nor input, nor help from said OEM, is sufficient to qualify for "uses ROS in their/with their products"?

If the answer is *yes*, I'll stop posting here.

**Comment by vmayoral** [comment]
> Do you believe a reference by an OEM to something which received no support, nor input, nor help from said OEM, is sufficient to qualify for "uses ROS in their/with their products"?

You have a point @gavanderhoorn.  This in my opinion wouldn't be a good enough reason. Yet, what got me to write the text above is that they claim "our ROS package" in their [response](https://dof.robotiq.com/discussion/2634/how-to-communicate-to-the-robotiq-2f-85-gripper-via-ros-melodic-and-ur10e):

>  To control the gripper via ros using **our ROS package**, you need to have it connected directly on your PC.
http://wiki.ros.org/robotiq

Another one that I found interesting [here](https://dof.robotiq.com/discussion/2507/how-to-control-robotiq-85-by-programming-in-ros-like-using-moveit-to-control-ur-manipulator):

>  For ROS **we** only provide the package you tried. I should work fine.
https://wiki.ros.org/robotiq

I guess you're probably the best person to argue the claims above 😄, but it appears they feel it's theirs (I guess interpreted for *their technology*). Confirmation of ownership (and responsibility) feels to me like something that should  qualify. It's I believe a confirmation that they're actually using ROS, even if they're not the original authors of the corresponding packages.

Anyhow, I looked at this a bit deeper and here's what I found:

- 40+ ROS-tagged posts in Robotiq's official support forum/discussion. Many have received professional support ([link](https://dof.robotiq.com/discussions/tagged/Other-ROS)). Besides ROS, they mention also rviz, and other tools of the ROS ecosystem.
- Robotiq reporting about its membership in ROS-Industrial (and thereby supporting ROS in Industry) ([link](https://blog.robotiq.com/bid/72049/ROS-Package-for-Robotiq-Grippers)).

With all this, do you believe it's acceptable to claim they are "using ROS" @gavanderhoorn?

**Comment by gavanderhoorn** [comment]
Robotiq did contribute to the packages in the past. However, it's been minimal, and until jproberge (who was not employed by Robotiq) stepped up, there was no direct involvement for at least 5 years (approximately).

There hasn't been any involvement in the past 2 years either any more.

The employees and posts you quote may not be aware their company is not supporting anything any more.

> With all this, do you believe it's acceptable to claim they are "using ROS" @gavanderhoorn?

tbh, no, I don't believe they are *using* ROS. They are still benefiting from the fact many community members have created packages for their hw, and the fact that they've, in the distant past, contributed to some small part of that.

It could be they're supporting, maintaining or developing ROS software in other repositories that I'm not aware of, but then I would not understand the reference to `wiki.ros.org/robotiq`.

But this has already cost more energy than it's worth, so let's give Robotiq the benefit of the doubt. At least they appear to be answering questions from their customers about ROS.

**Comment by gavanderhoorn** [comment]
Forgot to respond to this:

> Robotiq reporting about its membership in ROS-Industrial (and thereby supporting ROS in Industry)

the post you link to is from

> Posted on Aug 12, 2014 8:00 AM

that's almost 9 years ago. Last update: 2016.

As I wrote, let's not spend any more time on this, but I do believe a more strict evaluation of the criteria is in order.

Just listing any and all companies on there with some ROS exposure devalues the fact *actual* ROS supporting/using/contributing companies are listed.
