### ISSUE TITLE
Remove STAUBLI

### ISSUE THREAD

**Issue by gavanderhoorn** [vmayoral/ros-robotics-companies#72]
Similar to #70 and #71: STAUBLI should not be on this list.

`ros-industrial/staubli`, `ros-industrial/staubli_experimental` and `ros-industrial/staubli_val3_driver` are purely community projects.

There is no involvement of nor support from STAUBLI directly.

If the only evidence of use-of/support-of ROS was the fact `ros-industrial/staubli` exists, the STAUBLI entry on this list should be removed.

**Comment by gavanderhoorn** [comment]
Similar to #73, STAUBLI should also be removed from the *Manipulation* section.

The fact a single MoveIt configuration exists -- one I personally created back in 2014 (!) -- cannot be sufficient to state:

> The company uses the ROS Manipulation stack (MoveIt) in the rx160

additionally: "uses X in Y" really means: "STAUBLI, as part of its control software for their CS8 and CS9 series of industrial robot controllers integrates MoveIt and has the control software *use* MoveIt to control their robots, among which is the RX160 series of manipulators". That is patently false.

**Comment by pabloaccelerationrobotics** [comment]
Removed
