### ISSUE TITLE
Criteria for companies to appear on this list?

### ISSUE THREAD

**Issue by gavanderhoorn** [vmayoral/ros-robotics-companies#74]
After #70 caught my eye, I went over the list a bit more and noticed there are some entries which are at least *debatable* (#71, #72, #73).

I'd like as much as anyone here to see as many companies listed as possible, but it does seem like it would only be really valuable if the list is accurate and honest.

The readme states:

> A public list of companies that are known to use the Robot Operating System (ROS and ROS 2) or any of its related tools for development, to create products or to offer services.

the most important word here is probably *known*.

In the case of the issues I raised, I'm wondering whether the 'source data' used to justify a specific company being on the list was sufficient or even made sense. The references at the end of the document help, but in quite a few cases there are none, while some bold statements are made ("X uses ROS in product Y", "X supports ROS", "X makes use of ROS in Y", etc).

Would it be an idea to more clearly state the criteria used when determining whether a company could/should appear on the list? This could help avoid things like #70, #71, #72 and #73.

**Comment by gavanderhoorn** [comment]
There appear to be a number of companies for which the main rationale for inclusion seems to be (one of) their products being listed on `moveit.ros.org/robots`.

That list is completely community maintained (ie: anyone who just created a MoveIt configuration and pushed it to their personal GitHub/Gitlab/etc account can get it listed there), and was initially created by the (then) MoveIt maintainers (including me) based on whether or not there was at least a single MoveIt configuration packages "somewhere on the internet".

It might be prudent to remove, or at least review, the entries on the list for which their appearance on `moveit.ros.org/robots` is the sole justification.

**Comment by vmayoral** [comment]
Reading the concerns above, I believe it's pretty obvious we need a Criteria subsection. I made a first attempt at a4789f6913c1a775e3528d0fc3ad6104170c0c96.

@gavanderhoorn and @pabloaccelerationrobotics, can you have a look and share your thoughts on this?

> It might be prudent to remove, or at least review, the entries on the list for which their appearance on moveit.ros.org/robots is the sole justification.

Agreed. @pabloaccelerationrobotics any chance you could spare some time and look through this list once we agree on the criteria above?

**Comment by pabloaccelerationrobotics** [comment]
I agree with the new criteria. In the next few days/weeks, I will do a review of all the companies that appear on the list. Those that do not complete the requirements will be eliminated.

**Comment by vmayoral** [comment]
Criteria's now on `main` branch.

Closing here @gavanderhoorn, feel free to re-open and/or send PR if you have further suggestions.

**Comment by gavanderhoorn** [comment]
The added section seems like a good start indeed.

Two nits: criteria is plural, so `is -> are`, and:

> The company must be known to use ROS or ROS 2 for development, to create products or to offer services

the way this is phrased seems to exclude companies who ship ROS *with* or *as part of* their product(s). That's probably not what you meant.

**Comment by vmayoral** [comment]
> Two nits: criteria is plural, so is -> are, and:

Thanks! Tried incorporating the feedback at 14c96b22f668338ba3170736f10a06f89ae9a7f8
