### ISSUE TITLE
Correct phrasing "company X uses Y in Z" (Manipulation section)

### ISSUE THREAD

**Issue by gavanderhoorn** [vmayoral/ros-robotics-companies#75]
As mentioned in #74 (and examples in #73 and #72), the phrasing

> The company uses the ROS Manipulation stack (MoveIt) in X

appears in quite a few places in the list, specifically the *Manipulation* section.

For at least the companies where references are made to repositories under the `ros-industrial` GitHub organisation, none of these claims are correct.

This could be just the exact wording of the sentence, so perhaps just rephrasing it to something like "there are configuration packages for MoveIt available for the product of company Y" would be more correct. But I guess that wouldn't work, as it would put the bar very low for companies to appear on the list.

**Comment by vmayoral** [comment]
> This could be just the exact wording of the sentence, so perhaps just rephrasing it to something like "there are configuration packages for MoveIt available for the product of company Y" would be more correct. But I guess that wouldn't work, as it would put the bar very low for companies to appear on the list.

I think we should agree on a [criteria](https://github.com/vmayoral/ros-robotics-companies/tree/country#criteria) and be consistent with it. I'd say once we address https://github.com/vmayoral/ros-robotics-companies/issues/74, we should make a pass and try to be consistent with it. If companies don't meet the criteria, then they should be removed.

**Comment by vmayoral** [comment]
[Criteria](https://github.com/vmayoral/ros-robotics-companies/tree/country#criteria) has been set. 

@pabloaccelerationrobotics, I believe you'll go through the list and address the concern raised above, right? Can you report in here once you've done that so that we try resolving this ticket?

**Comment by vmayoral** [comment]
@pabloaccelerationrobotics where are we with this? Did you manage to find time on your end and look at the list while following the [criteria](https://github.com/vmayoral/ros-robotics-companies/tree/country#criteria)?

**Comment by vmayoral** [comment]
@pabloaccelerationrobotics ping in here. Please let us know once you finish the review so that we can make another pass.

**Comment by pabloaccelerationrobotics** [comment]
The review of the list is already finished. Following the new criteria, I have changed the justification for why some companies were on the list. The companies that I have not found justification have been eliminated.

@vmayoral and @gavanderhoorn Can you review it?

**Comment by gavanderhoorn** [comment]
I don't really have time to go through all changes, but I did a spot check and I noticed you seemingly reverted some fixes that were made as a result of our earlier discussions.

See [here](https://github.com/vmayoral/ros-robotics-companies/commit/d325e2ecd01e398d46570457a5208a2e78728940#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L492) fi, which basically reinstates Robotiq as a "ROS using/supporting company".

**Comment by vmayoral** [comment]
> See [here](https://github.com/vmayoral/ros-robotics-companies/commit/d325e2ecd01e398d46570457a5208a2e78728940#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L492) fi, which basically reinstates Robotiq as a "ROS using/supporting company".

Reverted changes for Robotiq https://github.com/vmayoral/ros-robotics-companies/commit/f795e7e230520da654518e583544955aff99f197.

Thanks for the review @pabloaccelerationrobotics. Feel free to point out any further defects if you have time @gavanderhoorn.
