### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by Daviesss** [vmayoral/ros-robotics-companies#78]
Hello ,good morning this is  not an issue . Just a request for a company to be added to the list of ROS robot .At Islington Robotica, we primarily focus on Robotics, Automation and Information Technologies. We build beautiful and intuitive software with semi-autonomous machinery to serve the people and their industries. Robotics is in an industry quite different from any other and so our goal is to complement and add value with a fleet of service and utility Robots / Cobots.Our mission is to build beautiful and intuitive semi autonomous machinery to serve the people and their needs . We want to create harmony between humans and humanoid technology also ground robots (A.M.R) to create a world that works. We use Ros for our Navigation system as well as for tsome aspect of  control also we have integrated some A.I technology to our robots . Our primary goal is to make life easier and reduce the arduous tasks from our day-to-day routines.

You can check out our website -  www.islingtonrobotica.com  

Regards.

**Comment by vmayoral** [comment]
@Daviesss, feel free to send a Pull Request.
